name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
      - name: test markdown
        run: echo '### Ceci est le test markdown de JJL' >> $GITHUB_STEP_SUMMARY
